version: '3'
services:
  api-heroes-postgres:
    container_name: api-heroes-postgres
    build: .
    ports:
      - 3000:3000
    environment:
      # POSTGRES_DB: logi
      # POSTGRES_USER: anu
      # POSTGRES_PASSWORD: anu
      POSTGRES_HOST: postgres:anu@postgres:5432
      PORT: 3000
      
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: anu
      POSTGRES_DB: heroes
      